### ISSUE TITLE
GPU requirement

### ISSUE THREAD

**Issue by ariannaliu** [nupurkmr9/concept-ablation#1]
Thanks for your amazing work!

May I know that is the GPU requirements for training one ablation model? Can I failed training on 24GB GPU. Thanks a lot.

**Comment by nupurkmr9** [comment]
Hi, you can use our diffusers based code with xformers support to run it on a 24GB GPU. Example training command will be as shown [here](https://github.com/nupurkmr9/concept-ablation/tree/main/diffusers#training-using-diffusers-library). 
Let me know if you face any issues. Thanks.
