### ISSUE TITLE
FID scores

### ISSUE THREAD

**Issue by jijunhao** [nupurkmr9/concept-ablation#4]
This is a good jod！Great work! I am inspired by it.  However, I have some minor issues.
I'm curious about the difference between stable diffusion of CompVis and the diffusers in this repository. Are they different implementations of the same method? 
Another concern is whether fine-tuning ，even with regularization，would affect FID scores for other categories？

Thanks.

**Comment by nupurkmr9** [comment]
Hi, thanks for the interest in our work and sorry for the delayed response. 

The CompVis and diffusers are different implementations of the same method. The diffusers version also consists of chatGPT API to generate the prompts corresponding to the concept being ablated whereas CompVis implementation requires a text file with those prompts as an argument. 
Thus it might be easier to use one or the other implementation for ablating a new concept based on whether you want to provide your own prompts or have a chatGPT access key.

Regarding the FID scores for other categories, we calculated the FID on MSCOCO dataset and found no significant difference. Thus the ablation process probably doesn't affect the unrelated concepts.
